/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define calculadora 0x3012227
#define calculadora_versao_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define soma 1
extern  int * soma_1(int *, CLIENT *);
extern  int * soma_1_svc(int *, struct svc_req *);
#define subtrai 2
extern  int * subtrai_1(int *, CLIENT *);
extern  int * subtrai_1_svc(int *, struct svc_req *);
extern int calculadora_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define soma 1
extern  int * soma_1();
extern  int * soma_1_svc();
#define subtrai 2
extern  int * subtrai_1();
extern  int * subtrai_1_svc();
extern int calculadora_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
